### ISSUE TITLE
Make it easier to install two parallel clusters with the server role

### ISSUE THREAD

**Issue by derfian** [cendio/ansible-role-thinlinc-server#1]
The way we assign servers into a ThinLinc cluster is currently based on the thinlinc-masters and thinlinc-agents groups, which could limit the use of this if you have more than one cluster to install. There's probably a better way to do this that would allow us to install servers into different clusters with different settings.

**Comment by derfian** [comment]
One idea that's been stuck in my head is to have the cluster assignment as part of a host variable, which could be given like this in an inventory, or by any other means.

```
[thinlinc-servers]
some-master.example.com    thinlinc_cluster=c1
some-agent-1.example.com   thinlinc_cluster=c1
some-agent-2.example.com   thinlinc_cluster=c1
other-master.example.com   thinlinc_cluster=c2
other-agent-1.example.com  thinlinc_cluster=c2
other-agent-2.example.com  thinlinc_cluster=c2
```
I am not sure if this is the best approach, so I'm going to keep an eye out for other alternatives.

**Comment by derfian** [comment]
So after thinking about this for another while it would make more sense to "group" clusters based on a host group in Ansible. An obstacle for this is that I can't figure out a way to gather the agent servers within a clusters for a way to auto-assign /vsmserver/terminalservers so this will likely have to be exposed as a configurable variable for the user to fill in.

**Comment by doczkal** [comment]
Just an idea (I haven't verified this). I might work to use the following hosts file:

[thinlinc-servers:children]
Cluster1
Cluster2

[Cluster1:children]
cl1_master
cl1_agents

[Cluster2:children]
cl2_master
cl2_agents

[cl1_master]
some-master.example.com

[cl1_agents]
some-agent-1.example.com
some-agent-2.example.com

[cl2_master]
other-master.example.com

[cl2_agents]
other-agent-1.example.com
other-agent-2.example.com

**Comment by aeneby** [comment]
Another idea would be to separate this into two roles, one for master and one for agent. We could then stop hard-coding group names, and leave it up to the playbook to determine which groups of servers are agents, masters, or both.

You could also have one inventory file per cluster, which would provide a cleaner separation between them. Of course, these days we have subclusters to deal with as well...

**Comment by eoli3n** [comment]
What I did to support multiple clusters

Configure the inventory as 
```
# Cluster 1
[thinlinc_master_prep]
thinlinc-prep
[thinlinc_agent_prep]
thinlinc-prep

# Cluster 2
[thinlinc_master_u3_213]
thinlinc-master-u3-213
[thinlinc_agent_u3_213:children]
mut_u3_213

# Cluster 3
[thinlinc_master_u3_214]
thinlinc-master-u3-214
[thinlinc_agent_u3_214:children]
mut_u3_214

[thinlinc_masters:children]
thinlinc_master_prep
thinlinc_master_u3_213
thinlinc_master_u3_214

[thinlinc_agents:children]
thinlinc_agent_prep
thinlinc_agent_u3_213
thinlinc_agent_u3_214

[thinlinc:children]
thinlinc_masters
thinlinc_agents
```

Set a group_var, to dynamically extract the cluster
```
thinlinc_cluster: "{{ group_names | select('match','thinlinc_(master|agent)_') | map('regex_replace','thinlinc_(master|agent)_','') | first }}"
```

Then update the tasks as
```
- name: Configure /vsmagent/allowed_clients
  tlconfig:
    param: /vsmagent/allowed_clients
    value: "{{ groups['thinlinc_master_' + thinlinc_cluster] | default(['localhost'], true) | join(' ') }}"
  notify: restart vsmagent
  when: "'thinlinc_agent_' + thinlinc_cluster in group_names"

- name: Configure list of agent servers
  tlconfig:
    param: /subclusters/Default/agents
    value: "{{ groups['thinlinc_agent_' + thinlinc_cluster] | default(['localhost'], true) | join(' ') }}"
  notify: restart vsmserver
  when: "'thinlinc_master_' + thinlinc_cluster in group_names"
```
