### ISSUE TITLE
thinlinc_agent_hostname: null in defaults is not working

### ISSUE THREAD

**Issue by pewo** [cendio/ansible-role-thinlinc-server#29]
When declaring thinlinc_agent_hostname to null in defaults/main.yml.

```yaml
# The agent hostname to report to clients. If your server is behind a
# firewall with NAT, this must be set to an address that forwards to
# your server. See
# https://www.cendio.com/resources/docs/tag/network.html#network_nat
#
# The default value is null, which is equal to ansible_fqdn.
thinlinc_agent_hostname: null
```

```yaml
- name: Configure /vsmagent/agent_hostname
  tlconfig:
    param: /vsmagent/agent_hostname
    value: "{{ thinlinc_agent_hostname | default(ansible_facts['fqdn']) }}"
  notify: restart vsmagent
  when: "'thinlinc_agents' in group_names"

```

Will not work as intended, since thinlinc_agent_hostname is always defined.

```
TASK [ansible-role-thinlinc-server : Configure /vsmagent/agent_hostname] ******
fatal: [thinlinc-server]: FAILED! => changed=false
msg: Value  can't  be  empty
```

If i comment out thinlinc_agent_hostname in the defaults/main.yml or define it to something else it works like intended.

```
ansible [core 2.14.2]
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  python version = 3.11.2 (main, Feb 18 2023, 08:12:16) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.11)
  jinja version = 3.1.2
```
