### ISSUE TITLE
Missing default definition in templates/thinlinc-setup.answers.j2

### ISSUE THREAD

**Issue by pewo** [cendio/ansible-role-thinlinc-server#44]
Trying to install the latest thinlinc server 4.18.0.

When I run this role it throws me an error:
``` yaml
  cmd:
  - /opt/thinlinc/sbin/tl-setup
  - -a
  - /root/thinlinc-setup.answers
  delta: '0:00:01.953046'
  end: '2025-01-03 15:20:16.354405'
  msg: non-zero return code
  rc: 78
  start: '2025-01-03 15:20:14.401359'
  stderr: |-
    Unable to init server: Could not connect: Connection refused
    Unable to init server: Could not connect: Connection refused
    ERROR: No answer given for agent-hostname-choice - aborting.

```
That definitions is missing from the thinlinc-setup.answers.j2
Adding 
`agent-hostname-choice=hostname` to thinlinc-setup.answers.j2 makes it work again.

The tl-setup -g | --generate-answers,  generates a correct file including two new definitions.
```
# How to determine externally reachable hostname
#agent-hostname-choice=ip|hostname|manual

# Externally reachable hostname (only used if manual)
#manual-agent-hostname=<hostname>
```
